# Funding links for the OpenMeta project.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [jskrishna]
# open_collective: openmeta
# patreon: #
# custom: ["https://example.com/donate"]
