name: Coding standards

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: coding-standards-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: PHP coding standards
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          tools: cs2pr
          coverage: none
      - uses: ramsey/composer-install@v3
      - name: PHPCS
        run: |
          set -o pipefail
          vendor/bin/phpcs --report=checkstyle | cs2pr
